### obtener todos los estudiantes 
GET http://localhost:3000/estudiantes

### obtener todos los estudiantes por id
GET http://localhost:3000/estudiantes/4d1aefc0-65d7-45e6-8dc9-8b8d2bb8b432

### eliminar estudiantes
DELETE  http://localhost:3000/estudiantes/d024f868-19d4-4aa0-b54f-1445a5f1d8b2

### crear todos los estudiantes 
POST  http://localhost:3000/estudiantes
Content-Type: application/json

{
    "nombre": "Laura",
    "apellidos": "Rodríguez",
    "edad": 24,
    "profesion": "Psicóloga",
    "email": "laura.rodriguezz@example.com"
}

### crear todos los estudiantes sin datos
POST  http://localhost:3000/estudiantes
Content-Type: application/json